[package]
name = "ai-playground"
version = "0.1.0"
authors = ["Lennart Jern <lennart.jern@gmail.com>"]

[dependencies]
rand = "0.3" # Random numbers
rustc-serialize = "0.3"
# time = "0.1"

# Web stuff
iron = "0.5.1"
staticfile = "*"

[dependencies.mount]
git = "https://github.com/iron/mount.git"
